# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Tagiswild.tdrop
PackageVersion: 1.0.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: tdrop.exe
    PortableCommandAlias: tdrop
Commands:
  - tdrop
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/TAGISWILD/tdrop/releases/download/v1.0.1/tdrop-windows-x64.zip
    InstallerSha256: 50eec0220d0c3d72f8a32888bfdfa8c0b75e1811e755baee6e549f5a0179bfce
ManifestType: installer
ManifestVersion: 1.6.0
